# Generated by Django 2.1.3 on 2020-03-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='contract_approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合同审核时间'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='contract_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, '报名费'), (1, '学费'), (2, '退费')], default=0),
        ),
        migrations.AddField(
            model_name='classlist',
            name='contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ContractTemplate'),
        ),
    ]
